T7350 yml verification script
Screenly/cli pull request #86
Opened 2023-08-27 19:47 UTC by StanIwan

## What does this PR do?
https://phorge.wireload.net/T7350

This PR adds a `screenly.yml` verification script that uses schema similar to one that `snapcraft` uses (https://github.com/snapcore/snapcraft/blob/main/schema/snapcraft.json).

Script can be used to check if all required fields are present in `screenly.yml` and if their type is correct. The script returns exit code according to verification result for use in the CI and also prints all issues found in the `.yml. file.

## How has this been tested?
- Manual tests with `screenly.yml` that is created by the `CLI`

2023-08-27 19:51 UTC, StanIwan commented
@renatgalimov - I've used the approach that you advised, my main concerns here are:
- verification script requires `python` - I don't think that this can be easily done using bash alone
- verification script requires `jsonschema` Python package - which must be manually installed
- script assumes that it will be run from the `cli` directory - this could be fixed by 2 arguments (path to .yml file; path to schema) instead of current 1 (path to .yml file)

Please let me know what you think, if my changes are sufficient, I'll make this a `Ready for review` PR

2023-08-28 06:56 UTC, renatgalimov commented
@StanIwan , I like it!

2023-08-28 08:28 UTC, StanIwan commented
> Why is this in Python? The CLI is written in Rust. We want to use it like this `screenly edge-app lint`. Not a separate tool.

`lint in rust` and `lint as a command in the cli` was the info I was missing, I'll implement it as a rust function that can be also called as a cli command.

2023-08-28 09:15 UTC, sergey-borovkov requested changes
I guess this PR should be thrown away.

2023-08-28 09:42 UTC, StanIwan commented
> I guess this PR should be thrown away.

I'll just replace bash script with python with rust, serde crate allows me to use my current json schema and verify yaml.

2023-08-28 09:58 UTC, closed without merging